package com.example.network

object AppsScriptTemplates {

    /**
     * Complete, robust Google Apps Script for syncing Health Connect & Hevy data.
     * Supports:
     * 1. Google Sheets directly bound to the script (Extensions > Apps Script).
     * 2. Google Sheets located in the destination folder in Google Drive.
     * 3. Flat CSV files in Google Drive with in-place intra-day updates (upsert by Date/ID).
     * 4. Structured JSON records in Google Drive with in-place intra-day updates.
     * 5. Automatic 180-day Active File Retention & Yearly Archiving:
     *    - Current file contains max 180 days of data.
     *    - Older data is moved to archive file(s) in the same folder suffixed by year: [fileName]_[YYYY].[ext].
     *    - Each archive file is strictly capped by data from that specific year.
     * 6. Bulk history exports with batching, deduplication, and rate-friendly handling.
     */
    private val COMMON_APPS_SCRIPT_BODY = listOf(
        "function doPost(e) {",
        "  return handleWebhook(e);",
        "}",
        "",
        "function doGet(e) {",
        "  return ContentService.createTextOutput(JSON.stringify({ status: \"active\", message: \"Nalama Webhook is running\" }))",
        "    .setMimeType(ContentService.MimeType.JSON);",
        "}",
        "",
        "function handleWebhook(e) {",
        "  try {",
        "    if (!e || !e.postData || !e.postData.contents) {",
        "      return ContentService.createTextOutput(JSON.stringify({ status: \"error\", message: \"No post data received\" }))",
        "        .setMimeType(ContentService.MimeType.JSON);",
        "    }",
        "",
        "    var payload = JSON.parse(e.postData.contents);",
        "    var sourceApp = payload.sourceApp || \"HealthConnect\";",
        "    var folderPath = payload.folderPath || (sourceApp === \"Hevy\" ? \"nalama.family/imports/gym_workouts\" : \"nalama.family/imports/health_data\");",
        "    var format = payload.format || \"csv\";",
        "    var writeMode = payload.writeMode || \"append\";",
        "    var fileName = payload.fileName || (sourceApp === \"Hevy\" ? \"hevy_workouts\" : \"biometrics_daily\");",
        "    var archiveMaxDays = payload.archiveMaxDays || 180;",
        "",
        "    var filesUpdated = [];",
        "",
        "    // 1. Support Google Sheet directly bound to script (Extensions > Apps Script)",
        "    try {",
        "      var activeSs = SpreadsheetApp.getActiveSpreadsheet();",
        "      if (activeSs) {",
        "        writeToSheet(activeSs.getActiveSheet(), payload, writeMode);",
        "        filesUpdated.push(\"Active Sheet: \" + activeSs.getName());",
        "      }",
        "    } catch (ssErr) {}",
        "",
        "    // 2. Locate or create destination folder in Google Drive",
        "    var folder = DriveApp.getRootFolder();",
        "    var parts = folderPath.split(\"/\");",
        "    for (var i = 0; i < parts.length; i++) {",
        "      var name = parts[i].trim();",
        "      if (!name) continue;",
        "      var sub = folder.getFoldersByName(name);",
        "      folder = sub.hasNext() ? sub.next() : folder.createFolder(name);",
        "    }",
        "",
        "    // 3. Support Google Sheet in target Drive folder",
        "    try {",
        "      var driveSheetFiles = folder.getFilesByType(MimeType.GOOGLE_SHEETS);",
        "      while (driveSheetFiles.hasNext()) {",
        "        var sf = driveSheetFiles.next();",
        "        var sName = sf.getName();",
        "        if (sName === fileName || sName === (fileName + \".csv\") || sName.indexOf(fileName) !== -1) {",
        "          var targetSs = SpreadsheetApp.openById(sf.getId());",
        "          writeToSheet(targetSs.getActiveSheet(), payload, writeMode);",
        "          filesUpdated.push(\"Drive Sheet: \" + sName);",
        "          break;",
        "        }",
        "      }",
        "    } catch (dsErr) {}",
        "",
        "    // 4. Update CSV File in Google Drive (In-place intra-day update by Date / Workout ID)",
        "    if (format === \"csv\" || format === \"both\" || filesUpdated.length === 0) {",
        "      var csvName = fileName + \".csv\";",
        "      var csvFiles = folder.getFilesByName(csvName);",
        "      var csvContent = payload.csvData || \"\";",
        "",
        "      if (csvFiles.hasNext()) {",
        "        var cf = csvFiles.next();",
        "        if (writeMode === \"append\") {",
        "          var oldText = cf.getBlob().getDataAsString();",
        "          var newLines = csvContent.trim().split(\"\\n\");",
        "          if (!oldText || oldText.trim().length === 0) {",
        "            cf.setContent(csvContent);",
        "            filesUpdated.push(csvName + \" (created)\");",
        "          } else {",
        "            var existingLines = oldText.trim().split(\"\\n\");",
        "            var keyLineMap = {};",
        "            for (var k = 1; k < existingLines.length; k++) {",
        "              var eLine = existingLines[k].trim();",
        "              if (!eLine) continue;",
        "              var eKey = eLine.split(\",\")[0].trim().replace(/^\\\"|\\\"$/g, \"\");",
        "              if (eKey) keyLineMap[eKey] = k;",
        "            }",
        "            var updatedCount = 0;",
        "            var appendedCount = 0;",
        "            for (var j = 0; j < newLines.length; j++) {",
        "              var nLine = newLines[j].trim();",
        "              if (!nLine) continue;",
        "              if (j === 0 && (nLine.toLowerCase().startsWith(\"date\") || nLine.toLowerCase().startsWith(\"workout_id\"))) {",
        "                continue;",
        "              }",
        "              var nKey = nLine.split(\",\")[0].trim().replace(/^\\\"|\\\"$/g, \"\");",
        "              if (nKey && keyLineMap[nKey] !== undefined) {",
        "                existingLines[keyLineMap[nKey]] = nLine;",
        "                updatedCount++;",
        "              } else {",
        "                existingLines.push(nLine);",
        "                if (nKey) keyLineMap[nKey] = existingLines.length - 1;",
        "                appendedCount++;",
        "              }",
        "            }",
        "            cf.setContent(existingLines.join(\"\\n\") + \"\\n\");",
        "            filesUpdated.push(csvName + \" (in-place: \" + updatedCount + \" updated, \" + appendedCount + \" new)\");",
        "          }",
        "        } else {",
        "          cf.setContent(csvContent);",
        "          filesUpdated.push(csvName + \" (overwritten)\");",
        "        }",
        "      } else {",
        "        folder.createFile(csvName, csvContent, MimeType.CSV);",
        "        filesUpdated.push(csvName + \" (created)\");",
        "      }",
        "    }",
        "",
        "    // 5. Update JSON File in Google Drive (In-place intra-day update by Date / Workout ID)",
        "    if (format === \"json\" || format === \"both\") {",
        "      var jsonName = fileName + \".json\";",
        "      var jsonFiles = folder.getFilesByName(jsonName);",
        "      var jsonStr = typeof payload.jsonData === \"string\" ? payload.jsonData : JSON.stringify(payload.jsonData, null, 2);",
        "",
        "      if (jsonFiles.hasNext() && writeMode === \"append\") {",
        "        var jf = jsonFiles.next();",
        "        try {",
        "          var old = JSON.parse(jf.getBlob().getDataAsString());",
        "          if (sourceApp === \"Hevy\" && old.workouts && payload.jsonData && payload.jsonData.workouts) {",
        "            var workoutMap = {};",
        "            old.workouts.forEach(function(w, idx) {",
        "              if (w.workoutId) workoutMap[w.workoutId] = idx;",
        "            });",
        "            var wUpdated = 0;",
        "            var wAppended = 0;",
        "            payload.jsonData.workouts.forEach(function(w) {",
        "              if (w.workoutId && workoutMap[w.workoutId] !== undefined) {",
        "                old.workouts[workoutMap[w.workoutId]] = w;",
        "                wUpdated++;",
        "              } else {",
        "                old.workouts.push(w);",
        "                if (w.workoutId) workoutMap[w.workoutId] = old.workouts.length - 1;",
        "                wAppended++;",
        "              }",
        "            });",
        "            old.syncedAt = payload.syncedAt || new Date().toISOString();",
        "            jf.setContent(JSON.stringify(old, null, 2));",
        "            filesUpdated.push(jsonName + \" (in-place: \" + wUpdated + \" updated, \" + wAppended + \" new)\");",
        "          } else if (old.dailyRecords && payload.jsonData && payload.jsonData.dailyRecords) {",
        "            var recMap = {};",
        "            old.dailyRecords.forEach(function(r, idx) {",
        "              if (r.date) recMap[r.date] = idx;",
        "            });",
        "            var rUpdated = 0;",
        "            var rAppended = 0;",
        "            payload.jsonData.dailyRecords.forEach(function(rec) {",
        "              if (rec.date && recMap[rec.date] !== undefined) {",
        "                old.dailyRecords[recMap[rec.date]] = rec;",
        "                rUpdated++;",
        "              } else {",
        "                old.dailyRecords.push(rec);",
        "                if (rec.date) recMap[rec.date] = old.dailyRecords.length - 1;",
        "                rAppended++;",
        "              }",
        "            });",
        "            old.exportedAt = payload.exportedAt;",
        "            jf.setContent(JSON.stringify(old, null, 2));",
        "            filesUpdated.push(jsonName + \" (in-place: \" + rUpdated + \" updated, \" + rAppended + \" new)\");",
        "          } else {",
        "            jf.setContent(jsonStr);",
        "            filesUpdated.push(jsonName + \" (saved)\");",
        "          }",
        "        } catch (err) {",
        "          jf.setContent(jsonStr);",
        "          filesUpdated.push(jsonName + \" (reset on error)\");",
        "        }",
        "      } else if (jsonFiles.hasNext()) {",
        "        jsonFiles.next().setContent(jsonStr);",
        "        filesUpdated.push(jsonName + \" (overwritten)\");",
        "      } else {",
        "        folder.createFile(jsonName, jsonStr, MimeType.PLAIN_TEXT);",
        "        filesUpdated.push(jsonName + \" (created)\");",
        "      }",
        "    }",
        "",
        "    // 6. Enforce 180-day max retention on active files & partition older records into [fileName]_[YYYY].[ext]",
        "    try {",
        "      archiveOldRecords(folder, fileName, format, sourceApp, archiveMaxDays, filesUpdated);",
        "    } catch (archErr) {",
        "      filesUpdated.push(\"Archive check note: \" + archErr.toString());",
        "    }",
        "",
        "    return ContentService.createTextOutput(JSON.stringify({",
        "      status: \"success\",",
        "      sourceApp: sourceApp,",
        "      message: \"Export processed successfully\",",
        "      folder: folderPath,",
        "      files: filesUpdated,",
        "      recordsCount: payload.recordsCount || 1",
        "    })).setMimeType(ContentService.MimeType.JSON);",
        "",
        "  } catch (err) {",
        "    return ContentService.createTextOutput(JSON.stringify({",
        "      status: \"error\",",
        "      message: err.toString()",
        "    })).setMimeType(ContentService.MimeType.JSON);",
        "  }",
        "}",
        "",
        "/**",
        " * Enforces max 180 days retention on current file.",
        " * Moves older records to archive files in the same folder, suffixed by year: [fileName]_[YYYY].[ext]",
        " * Each archive file is capped by data only from that specific year.",
        " */",
        "function archiveOldRecords(folder, fileName, format, sourceApp, maxDays, filesUpdated) {",
        "  var limit = maxDays || 180;",
        "  var cutoff = new Date();",
        "  cutoff.setDate(cutoff.getDate() - limit);",
        "  var cutoffStr = Utilities.formatDate(cutoff, \"GMT\", \"yyyy-MM-dd\");",
        "  var isHevy = (sourceApp === \"Hevy\");",
        "",
        "  // 1. Archive CSV File",
        "  if (format === \"csv\" || format === \"both\") {",
        "    var csvName = fileName + \".csv\";",
        "    var files = folder.getFilesByName(csvName);",
        "    if (files.hasNext()) {",
        "      var cf = files.next();",
        "      var content = cf.getBlob().getDataAsString();",
        "      var lines = content.trim().split(\"\\n\");",
        "      if (lines.length > 1) {",
        "        var header = lines[0];",
        "        var keptLines = [header];",
        "        var archivesByYear = {};",
        "",
        "        for (var i = 1; i < lines.length; i++) {",
        "          var line = lines[i].trim();",
        "          if (!line) continue;",
        "          var cols = line.split(\",\");",
        "          var rawDate = isHevy ? (cols[1] || \"\") : (cols[0] || \"\");",
        "          var dateStr = rawDate.replace(/^\\\"|\\\"$/g, \"\").trim().substring(0, 10);",
        "",
        "          if (dateStr && dateStr.length === 10 && dateStr < cutoffStr) {",
        "            var yr = dateStr.substring(0, 4);",
        "            if (!archivesByYear[yr]) archivesByYear[yr] = [];",
        "            archivesByYear[yr].push(line);",
        "          } else {",
        "            keptLines.push(line);",
        "          }",
        "        }",
        "",
        "        var years = Object.keys(archivesByYear);",
        "        if (years.length > 0) {",
        "          for (var y = 0; y < years.length; y++) {",
        "            var yr = years[y];",
        "            var archCsvName = fileName + \"_\" + yr + \".csv\";",
        "            var archFiles = folder.getFilesByName(archCsvName);",
        "            var toArchive = archivesByYear[yr];",
        "",
        "            if (archFiles.hasNext()) {",
        "              var af = archFiles.next();",
        "              var exText = af.getBlob().getDataAsString().trim();",
        "              var exLines = exText ? exText.split(\"\\n\") : [header];",
        "              var keyMap = {};",
        "              for (var k = 1; k < exLines.length; k++) {",
        "                var kKey = exLines[k].split(\",\")[0].replace(/^\\\"|\\\"$/g, \"\").trim();",
        "                if (kKey) keyMap[kKey] = k;",
        "              }",
        "              for (var a = 0; a < toArchive.length; a++) {",
        "                var aLine = toArchive[a];",
        "                var aKey = aLine.split(\",\")[0].replace(/^\\\"|\\\"$/g, \"\").trim();",
        "                if (aKey && keyMap[aKey] !== undefined) {",
        "                  exLines[keyMap[aKey]] = aLine;",
        "                } else {",
        "                  exLines.push(aLine);",
        "                  if (aKey) keyMap[aKey] = exLines.length - 1;",
        "                }",
        "              }",
        "              af.setContent(exLines.join(\"\\n\") + \"\\n\");",
        "              filesUpdated.push(archCsvName + \" (archived \" + toArchive.length + \" rows from \" + yr + \")\");",
        "            } else {",
        "              folder.createFile(archCsvName, header + \"\\n\" + toArchive.join(\"\\n\") + \"\\n\", MimeType.CSV);",
        "              filesUpdated.push(archCsvName + \" (created archive for \" + yr + \": \" + toArchive.length + \" rows)\");",
        "            }",
        "          }",
        "          cf.setContent(keptLines.join(\"\\n\") + \"\\n\");",
        "          filesUpdated.push(csvName + \" (active window: \" + (keptLines.length - 1) + \" days retained)\");",
        "        }",
        "      }",
        "    }",
        "  }",
        "",
        "  // 2. Archive JSON File",
        "  if (format === \"json\" || format === \"both\") {",
        "    var jsonName = fileName + \".json\";",
        "    var jFiles = folder.getFilesByName(jsonName);",
        "    if (jFiles.hasNext()) {",
        "      var jf = jFiles.next();",
        "      try {",
        "        var data = JSON.parse(jf.getBlob().getDataAsString());",
        "        var list = isHevy ? data.workouts : data.dailyRecords;",
        "        if (list && list.length > 0) {",
        "          var keptItems = [];",
        "          var archJson = {};",
        "          for (var r = 0; r < list.length; r++) {",
        "            var item = list[r];",
        "            var itemDate = (item.date || \"\").trim().substring(0, 10);",
        "            if (itemDate && itemDate.length === 10 && itemDate < cutoffStr) {",
        "              var yr = itemDate.substring(0, 4);",
        "              if (!archJson[yr]) archJson[yr] = [];",
        "              archJson[yr].push(item);",
        "            } else {",
        "              keptItems.push(item);",
        "            }",
        "          }",
        "",
        "          var jYears = Object.keys(archJson);",
        "          if (jYears.length > 0) {",
        "            for (var y = 0; y < jYears.length; y++) {",
        "              var yr = jYears[y];",
        "              var aName = fileName + \"_\" + yr + \".json\";",
        "              var aFiles = folder.getFilesByName(aName);",
        "              var itemsToArchive = archJson[yr];",
        "",
        "              if (aFiles.hasNext()) {",
        "                var af = aFiles.next();",
        "                try {",
        "                  var aData = JSON.parse(af.getBlob().getDataAsString());",
        "                  var aList = isHevy ? (aData.workouts || []) : (aData.dailyRecords || []);",
        "                  var aKeyMap = {};",
        "                  aList.forEach(function(it, idx) {",
        "                    var k = isHevy ? it.workoutId : it.date;",
        "                    if (k) aKeyMap[k] = idx;",
        "                  });",
        "                  itemsToArchive.forEach(function(it) {",
        "                    var k = isHevy ? it.workoutId : it.date;",
        "                    if (k && aKeyMap[k] !== undefined) {",
        "                      aList[aKeyMap[k]] = it;",
        "                    } else {",
        "                      aList.push(it);",
        "                      if (k) aKeyMap[k] = aList.length - 1;",
        "                    }",
        "                  });",
        "                  if (isHevy) aData.workouts = aList; else aData.dailyRecords = aList;",
        "                  af.setContent(JSON.stringify(aData, null, 2));",
        "                  filesUpdated.push(aName + \" (archived \" + itemsToArchive.length + \" items)\");",
        "                } catch (e) {}",
        "              } else {",
        "                var newArchObj = {",
        "                  exportVersion: data.exportVersion || \"1.0\",",
        "                  sourceApp: sourceApp,",
        "                  archiveYear: parseInt(yr, 10),",
        "                  archivedAt: new Date().toISOString()",
        "                };",
        "                if (isHevy) newArchObj.workouts = itemsToArchive; else newArchObj.dailyRecords = itemsToArchive;",
        "                folder.createFile(aName, JSON.stringify(newArchObj, null, 2), MimeType.PLAIN_TEXT);",
        "                filesUpdated.push(aName + \" (created archive for \" + yr + \": \" + itemsToArchive.length + \" items)\");",
        "              }",
        "            }",
        "            if (isHevy) data.workouts = keptItems; else data.dailyRecords = keptItems;",
        "            jf.setContent(JSON.stringify(data, null, 2));",
        "            filesUpdated.push(jsonName + \" (active window: \" + keptItems.length + \" items retained)\");",
        "          }",
        "        }",
        "      } catch (e) {}",
        "    }",
        "  }",
        "}",
        "",
        "function writeToSheet(sheet, payload, writeMode) {",
        "  var headers = payload.sheetHeaders;",
        "  var rows = payload.sheetRows;",
        "",
        "  if (!rows || rows.length === 0) {",
        "    var rawLines = (payload.csvData || \"\").trim().split(\"\\n\");",
        "    if (rawLines.length > 0) {",
        "      if (!headers || headers.length === 0) headers = rawLines[0].split(\",\");",
        "      rows = [];",
        "      for (var i = 1; i < rawLines.length; i++) {",
        "        if (rawLines[i].trim()) rows.push(rawLines[i].split(\",\"));",
        "      }",
        "    }",
        "  }",
        "",
        "  if (sheet.getLastRow() === 0 && headers && headers.length > 0) {",
        "    sheet.appendRow(headers);",
        "    sheet.getRange(1, 1, 1, headers.length).setFontWeight(\"bold\");",
        "    sheet.setFrozenRows(1);",
        "  }",
        "",
        "  if (!rows || rows.length === 0) return;",
        "",
        "  if (writeMode === \"overwrite\") {",
        "    if (sheet.getLastRow() > 1) sheet.deleteRows(2, sheet.getLastRow() - 1);",
        "    for (var r = 0; r < rows.length; r++) {",
        "      sheet.appendRow(rows[r]);",
        "    }",
        "  } else {",
        "    var lastRow = sheet.getLastRow();",
        "    var existingKeys = {};",
        "    if (lastRow > 1) {",
        "      var keyValues = sheet.getRange(2, 1, lastRow - 1, 1).getValues();",
        "      for (var k = 0; k < keyValues.length; k++) {",
        "        var val = String(keyValues[k][0]).trim();",
        "        if (val) existingKeys[val] = k + 2;",
        "      }",
        "    }",
        "    for (var r = 0; r < rows.length; r++) {",
        "      var row = rows[r];",
        "      var key = String(row[0]).trim();",
        "      if (existingKeys[key]) {",
        "        sheet.getRange(existingKeys[key], 1, 1, row.length).setValues([row]);",
        "      } else {",
        "        sheet.appendRow(row);",
        "        existingKeys[key] = sheet.getLastRow();",
        "      }",
        "    }",
        "  }",
        "}"
    )

    /**
     * Contents to paste directly inside the default myFunction() { ... } created by Google Apps Script.
     */
    val MY_FUNCTION_APPS_SCRIPT_CONTENT: String = (listOf(
        "  return handleWebhook(arguments[0]);",
        "}",
        ""
    ) + COMMON_APPS_SCRIPT_BODY).joinToString("\n")

    /**
     * Standalone complete script.
     */
    val FULL_APPS_SCRIPT_CODE: String = (listOf(
        "/**",
        " * Google Apps Script Webhook Handler for Health Connect & Hevy Gym Sync",
        " * Nalama Companion (nalama.family)",
        " * Features: Intra-day In-Place Updates (Upsert) + 180-Day Retention + Yearly Archive",
        " */",
        ""
    ) + COMMON_APPS_SCRIPT_BODY).joinToString("\n")

    val SAMPLE_APPS_SCRIPT_CODE: String = MY_FUNCTION_APPS_SCRIPT_CONTENT
}
