package com.example.network

object AppsScriptTemplates {

    /**
     * Complete, robust Google Apps Script for syncing Health Connect & Hevy data.
     * Supports:
     * 1. Google Sheets directly bound to the script (Extensions > Apps Script).
     * 2. Google Sheets located in the destination folder in Google Drive.
     * 3. Flat CSV files in Google Drive (with proper header handling and line appending).
     * 4. Structured JSON records in Google Drive.
     */
    private val COMMON_APPS_SCRIPT_BODY = listOf(
        "function doPost(e) {",
        "  return handleWebhook(e);",
        "}",
        "",
        "function doGet(e) {",
        "  return ContentService.createTextOutput(JSON.stringify({ status: \"active\", message: \"Nalama Webhook is running\" }))",
        "    .setMimeType(ContentService.MimeType.JSON);",
        "}",
        "",
        "function handleWebhook(e) {",
        "  try {",
        "    if (!e || !e.postData || !e.postData.contents) {",
        "      return ContentService.createTextOutput(JSON.stringify({ status: \"error\", message: \"No post data received\" }))",
        "        .setMimeType(ContentService.MimeType.JSON);",
        "    }",
        "",
        "    var payload = JSON.parse(e.postData.contents);",
        "    var sourceApp = payload.sourceApp || \"HealthConnect\";",
        "    var folderPath = payload.folderPath || (sourceApp === \"Hevy\" ? \"nalama.family/imports/gym_workouts\" : \"nalama.family/imports/health_data\");",
        "    var format = payload.format || \"csv\";",
        "    var writeMode = payload.writeMode || \"append\";",
        "    var fileName = payload.fileName || (sourceApp === \"Hevy\" ? \"hevy_workouts\" : \"biometrics_daily\");",
        "",
        "    var filesUpdated = [];",
        "",
        "    // 1. Support Google Sheet directly bound to script (Extensions > Apps Script)",
        "    try {",
        "      var activeSs = SpreadsheetApp.getActiveSpreadsheet();",
        "      if (activeSs) {",
        "        writeToSheet(activeSs.getActiveSheet(), payload, writeMode);",
        "        filesUpdated.push(\"Active Sheet: \" + activeSs.getName());",
        "      }",
        "    } catch (ssErr) {}",
        "",
        "    // 2. Locate or create destination folder in Google Drive",
        "    var folder = DriveApp.getRootFolder();",
        "    var parts = folderPath.split(\"/\");",
        "    for (var i = 0; i < parts.length; i++) {",
        "      var name = parts[i].trim();",
        "      if (!name) continue;",
        "      var sub = folder.getFoldersByName(name);",
        "      folder = sub.hasNext() ? sub.next() : folder.createFolder(name);",
        "    }",
        "",
        "    // 3. Support Google Sheet in target Drive folder",
        "    try {",
        "      var driveSheetFiles = folder.getFilesByType(MimeType.GOOGLE_SHEETS);",
        "      while (driveSheetFiles.hasNext()) {",
        "        var sf = driveSheetFiles.next();",
        "        var sName = sf.getName();",
        "        if (sName === fileName || sName === (fileName + \".csv\") || sName.indexOf(fileName) !== -1) {",
        "          var targetSs = SpreadsheetApp.openById(sf.getId());",
        "          writeToSheet(targetSs.getActiveSheet(), payload, writeMode);",
        "          filesUpdated.push(\"Drive Sheet: \" + sName);",
        "          break;",
        "        }",
        "      }",
        "    } catch (dsErr) {}",
        "",
        "    // 4. Update CSV File in Google Drive",
        "    if (format === \"csv\" || format === \"both\" || filesUpdated.length === 0) {",
        "      var csvName = fileName + \".csv\";",
        "      var csvFiles = folder.getFilesByName(csvName);",
        "      var csvContent = payload.csvData || \"\";",
        "",
        "      if (csvFiles.hasNext()) {",
        "        var cf = csvFiles.next();",
        "        if (writeMode === \"append\") {",
        "          var oldText = cf.getBlob().getDataAsString();",
        "          var newLines = csvContent.trim().split(\"\\n\");",
        "          if (!oldText || oldText.trim().length === 0) {",
        "            cf.setContent(csvContent);",
        "          } else {",
        "            var toAppend = [];",
        "            for (var j = 0; j < newLines.length; j++) {",
        "              var line = newLines[j].trim();",
        "              if (!line) continue;",
        "              if (j === 0 && (line.toLowerCase().startsWith(\"date\") || line.toLowerCase().startsWith(\"workout_id\"))) {",
        "                continue;",
        "              }",
        "              toAppend.push(line);",
        "            }",
        "            if (toAppend.length > 0) {",
        "              cf.setContent(oldText.trim() + \"\\n\" + toAppend.join(\"\\n\") + \"\\n\");",
        "            }",
        "          }",
        "          filesUpdated.push(csvName + \" (appended)\");",
        "        } else {",
        "          cf.setContent(csvContent);",
        "          filesUpdated.push(csvName + \" (overwritten)\");",
        "        }",
        "      } else {",
        "        folder.createFile(csvName, csvContent, MimeType.CSV);",
        "        filesUpdated.push(csvName + \" (created)\");",
        "      }",
        "    }",
        "",
        "    // 5. Update JSON File in Google Drive (if requested)",
        "    if (format === \"json\" || format === \"both\") {",
        "      var jsonName = fileName + \".json\";",
        "      var jsonFiles = folder.getFilesByName(jsonName);",
        "      var jsonStr = typeof payload.jsonData === \"string\" ? payload.jsonData : JSON.stringify(payload.jsonData, null, 2);",
        "",
        "      if (jsonFiles.hasNext() && writeMode === \"append\") {",
        "        var jf = jsonFiles.next();",
        "        try {",
        "          var old = JSON.parse(jf.getBlob().getDataAsString());",
        "          if (sourceApp === \"Hevy\" && old.workouts && payload.jsonData && payload.jsonData.workouts) {",
        "            var existingIds = new Set(old.workouts.map(function(w) { return w.workoutId; }));",
        "            payload.jsonData.workouts.forEach(function(w) {",
        "              if (!existingIds.has(w.workoutId)) old.workouts.push(w);",
        "            });",
        "            old.syncedAt = payload.syncedAt || new Date().toISOString();",
        "            jf.setContent(JSON.stringify(old, null, 2));",
        "          } else if (old.dailyRecords && payload.jsonData && payload.jsonData.dailyRecords) {",
        "            var existingDates = new Set(old.dailyRecords.map(function(r) { return r.date; }));",
        "            payload.jsonData.dailyRecords.forEach(function(rec) {",
        "              if (!existingDates.has(rec.date)) old.dailyRecords.push(rec);",
        "            });",
        "            old.exportedAt = payload.exportedAt;",
        "            jf.setContent(JSON.stringify(old, null, 2));",
        "          } else {",
        "            jf.setContent(jsonStr);",
        "          }",
        "        } catch (err) {",
        "          jf.setContent(jsonStr);",
        "        }",
        "        filesUpdated.push(jsonName + \" (appended)\");",
        "      } else if (jsonFiles.hasNext()) {",
        "        jsonFiles.next().setContent(jsonStr);",
        "        filesUpdated.push(jsonName + \" (overwritten)\");",
        "      } else {",
        "        folder.createFile(jsonName, jsonStr, MimeType.PLAIN_TEXT);",
        "        filesUpdated.push(jsonName + \" (created)\");",
        "      }",
        "    }",
        "",
        "    return ContentService.createTextOutput(JSON.stringify({",
        "      status: \"success\",",
        "      sourceApp: sourceApp,",
        "      message: \"Export processed successfully\",",
        "      folder: folderPath,",
        "      files: filesUpdated,",
        "      recordsCount: payload.recordsCount || 1",
        "    })).setMimeType(ContentService.MimeType.JSON);",
        "",
        "  } catch (err) {",
        "    return ContentService.createTextOutput(JSON.stringify({",
        "      status: \"error\",",
        "      message: err.toString()",
        "    })).setMimeType(ContentService.MimeType.JSON);",
        "  }",
        "}",
        "",
        "function writeToSheet(sheet, payload, writeMode) {",
        "  var headers = payload.sheetHeaders;",
        "  var rows = payload.sheetRows;",
        "",
        "  if (!rows || rows.length === 0) {",
        "    var rawLines = (payload.csvData || \"\").trim().split(\"\\n\");",
        "    if (rawLines.length > 0) {",
        "      if (!headers || headers.length === 0) headers = rawLines[0].split(\",\");",
        "      rows = [];",
        "      for (var i = 1; i < rawLines.length; i++) {",
        "        if (rawLines[i].trim()) rows.push(rawLines[i].split(\",\"));",
        "      }",
        "    }",
        "  }",
        "",
        "  if (sheet.getLastRow() === 0 && headers && headers.length > 0) {",
        "    sheet.appendRow(headers);",
        "    sheet.getRange(1, 1, 1, headers.length).setFontWeight(\"bold\");",
        "    sheet.setFrozenRows(1);",
        "  }",
        "",
        "  if (!rows || rows.length === 0) return;",
        "",
        "  if (writeMode === \"overwrite\") {",
        "    if (sheet.getLastRow() > 1) sheet.deleteRows(2, sheet.getLastRow() - 1);",
        "    for (var r = 0; r < rows.length; r++) {",
        "      sheet.appendRow(rows[r]);",
        "    }",
        "  } else {",
        "    var lastRow = sheet.getLastRow();",
        "    var existingKeys = {};",
        "    if (lastRow > 1) {",
        "      var keyValues = sheet.getRange(2, 1, lastRow - 1, 1).getValues();",
        "      for (var k = 0; k < keyValues.length; k++) {",
        "        var val = String(keyValues[k][0]).trim();",
        "        if (val) existingKeys[val] = k + 2;",
        "      }",
        "    }",
        "    for (var r = 0; r < rows.length; r++) {",
        "      var row = rows[r];",
        "      var key = String(row[0]).trim();",
        "      if (existingKeys[key]) {",
        "        sheet.getRange(existingKeys[key], 1, 1, row.length).setValues([row]);",
        "      } else {",
        "        sheet.appendRow(row);",
        "      }",
        "    }",
        "  }",
        "}"
    )

    /**
     * Contents to paste directly inside the default myFunction() { ... } created by Google Apps Script.
     */
    val MY_FUNCTION_APPS_SCRIPT_CONTENT: String = (listOf(
        "  return handleWebhook(arguments[0]);",
        "}",
        ""
    ) + COMMON_APPS_SCRIPT_BODY).joinToString("\n")

    /**
     * Standalone complete script.
     */
    val FULL_APPS_SCRIPT_CODE: String = (listOf(
        "/**",
        " * Google Apps Script Webhook Handler for Health Connect & Hevy Gym Sync",
        " * Nalama Companion (nalama.family)",
        " */",
        ""
    ) + COMMON_APPS_SCRIPT_BODY).joinToString("\n")

    val SAMPLE_APPS_SCRIPT_CODE: String = MY_FUNCTION_APPS_SCRIPT_CONTENT
}
